"""add_detection_signal_columns

Revision ID: 8f110729c9cf
Revises: 395f642c5ae5
Create Date: 2026-01-08 00:19:52.683849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f110729c9cf'
down_revision: Union[str, None] = '395f642c5ae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('detections', sa.Column('entropy_score', sa.Float(), nullable=True))
    op.add_column('detections', sa.Column('distance_score', sa.Float(), nullable=True))
    op.add_column('detections', sa.Column('signal_breakdown', sa.Text(), nullable=True))
    op.add_column('detections', sa.Column('priority_weights', sa.Text(), nullable=True))
    op.drop_table('playing_with_neon')
    op.drop_index('ix_experiments_dataset_id', table_name='experiments')
    op.drop_index('ix_experiments_id', table_name='experiments')
    op.drop_table('experiments')
    op.drop_index('ix_experiment_iterations_experiment_id', table_name='experiment_iterations')
    op.drop_index('ix_experiment_iterations_id', table_name='experiment_iterations')
    op.drop_table('experiment_iterations')
    op.add_column('detections', sa.Column('entropy_score', sa.Float(), nullable=True))
    op.add_column('detections', sa.Column('distance_score', sa.Float(), nullable=True))
    op.add_column('detections', sa.Column('signal_breakdown', sa.Text(), nullable=True))
    op.add_column('detections', sa.Column('priority_weights', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.create_table('experiment_iterations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('iteration_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('accuracy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('precision', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('recall', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('f1_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('samples_flagged', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('samples_corrected', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('correction_acceptance_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('remaining_noise_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('samples_reviewed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('iteration_time_seconds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='experiment_iterations_pkey')
    )
    op.create_index('ix_experiment_iterations_id', 'experiment_iterations', ['id'], unique=False)
    op.create_index('ix_experiment_iterations_experiment_id', 'experiment_iterations', ['experiment_id'], unique=False)
    op.create_table('experiments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dataset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('noise_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('detection_threshold', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('max_iterations', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_iteration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('baseline_accuracy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('final_accuracy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_corrections', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_time_seconds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('iteration_results', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='experiments_pkey')
    )
    op.create_index('ix_experiments_id', 'experiments', ['id'], unique=False)
    op.create_index('ix_experiments_dataset_id', 'experiments', ['dataset_id'], unique=False)
    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='playing_with_neon_pkey')
    )
    # ### end Alembic commands ###
